### ISSUE TITLE
A11 - Page détaillée d'un spectacle

### ISSUE THREAD

**Issue by judef1** [gti525/e18-vente1#5]
En tant qu'utilisateur, lorsque je consulte la page détaillée d'un spectable, il doit y avoir une vignette informative du spectacle (voir exigence technique)

**Comment by Nelm12** [comment]
Exigence Technique: Les informations sur un spectacle sont le titre du spectacle, l'artiste, la date, l'heure, un texte descriptif et l'identifiant unique de la salle. L'identifiant unique ne doit pas être visible pas l'utilisateur
